control flow
Unidata/online-python-training pull request #94
Opened 2017-01-01 22:24 UTC by julienchastang

Closes #6

2017-01-02 18:30 UTC, dopplershift requested changes
Overall these look great--just a few small edits.

2017-01-02 18:30 UTC, dopplershift commented on notebooks/Functions.ipynb
> +    "Armed with this knowledge, we can write a function called `uandv` to calculate the u and v vectors from wind speed and direction parameters:"
U and V are Cartesian components of the wind vector, not vectors themselves.

2017-01-02 18:30 UTC, dopplershift commented on notebooks/Functions.ipynb
> +    "    \"calculate u and v vectors from speed and direction\"\n",
Same as above.

2017-01-02 18:30 UTC, dopplershift commented on notebooks/Functions.ipynb
> +    "    return (u, v)"
Unless you feel passionately that the parentheses are important for pedagogical purposes, I'd remove them since they're unneeded.

2017-01-02 18:30 UTC, dopplershift commented on notebooks/Functions.ipynb
> +    "The `u` and `v` vectors are returned as [tuples](http://nbviewer.jupyter.org/github/Unidata/online-python-training/blob/master/notebooks/Basic%252520Data%252520Structures.ipynb#Tuples).\n",
Again as above.

2017-01-02 18:30 UTC, dopplershift commented on notebooks/Loops.ipynb
> +    "Take a closer look at the `for time, obs in data` statement. We could have written a statement such as `for observation in data` to retrieve each `observation` tuple in the series and subsequent
"append it to the `gusts` list..." if the wind speed exceeds the threshold.

2017-01-03 16:10 UTC, julienchastang commented on notebooks/Functions.ipynb
> +    "Armed with this knowledge, we can write a function called `uandv` to calculate the u and v vectors from wind speed and direction parameters:"
ok

2017-01-03 16:10 UTC, julienchastang commented on notebooks/Functions.ipynb
> +    "    \"calculate u and v vectors from speed and direction\"\n",
ok

2017-01-03 16:10 UTC, julienchastang commented on notebooks/Functions.ipynb
> +    "    return (u, v)"
ok

2017-01-03 16:10 UTC, julienchastang commented on notebooks/Functions.ipynb
> +    "The `u` and `v` vectors are returned as [tuples](http://nbviewer.jupyter.org/github/Unidata/online-python-training/blob/master/notebooks/Basic%252520Data%252520Structures.ipynb#Tuples).\n",
ok

2017-01-03 16:10 UTC, julienchastang commented on notebooks/Loops.ipynb
> +    "Take a closer look at the `for time, obs in data` statement. We could have written a statement such as `for observation in data` to retrieve each `observation` tuple in the series and subsequent
ok

2017-01-03 17:46 UTC, dopplershift approved these changes

2017-01-03 17:46 UTC, merged