control flow intro
Unidata/online-python-training pull request #95
Opened 2017-01-01 22:25 UTC by julienchastang

Closes #6

2017-01-02 18:35 UTC, dopplershift requested changes
Looks good, just a few little things.

2017-01-02 18:35 UTC, dopplershift commented on controlflowintro.md
> +In addition, control flow can also concern a program proceeding through a list of values or while some condition has not yet been met. A rawinsonde may send data until a certain pressure level has be
"or while some condition has not yet been"--maybe before this add something like "or continuing to execute a set of statements"

2017-01-02 18:35 UTC, dopplershift commented on controlflowintro.md
> +Control flow can be complex and programmers must learn to manage that complexity and keep it in check in order to write programs that can be understood by others and maintained in the long term. One
"such as unit conversion" -> "(e.g. unit conversion)"?

2017-01-02 18:35 UTC, dopplershift commented on controlflowintro.md
> +In this section, we will examine three notebooks on control flow. A notebook that examines [conditional statements](http://nbviewer.jupyter.org/github/Unidata/online-python-training/blob/master/noteb
"control flow." -> "control flow:"
"A notebook that" -> "one that"
"one makes" -> "one that makes"
?

2017-01-03 16:36 UTC, julienchastang commented on controlflowintro.md
> +In addition, control flow can also concern a program proceeding through a list of values or while some condition has not yet been met. A rawinsonde may send data until a certain pressure level has be
OK (I think). See edits.

2017-01-03 16:36 UTC, julienchastang commented on controlflowintro.md
> +Control flow can be complex and programmers must learn to manage that complexity and keep it in check in order to write programs that can be understood by others and maintained in the long term. One
ok

2017-01-03 16:36 UTC, julienchastang commented on controlflowintro.md
> +In this section, we will examine three notebooks on control flow. A notebook that examines [conditional statements](http://nbviewer.jupyter.org/github/Unidata/online-python-training/blob/master/noteb
ok

2017-01-03 17:43 UTC, dopplershift approved these changes

2017-01-03 17:44 UTC, dopplershift commented
Test failure just due to linking to through nbviewer to notebooks that aren't committed yet. (Would be nice to fix that...) Merging...

2017-01-03 17:45 UTC, merged